// Generates React Native piece components from the RhosGFX SVG sources.
//
// The conversion itself, shared with generate-faces.mjs, is in rhosgfx-svg.mjs.
//
// Run: node native/scripts/generate-pieces.mjs && npm run format
// The emitted files are checked in, and npm run format:check covers native/,
// so always format after regenerating or the gate will fail.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  byCodeUnit,
  convert,
  usedComponents,
  viewBoxOf,
} from './rhosgfx-svg.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SOURCE = join(root, 'src', 'assets', 'pieces', 'rhosgfx');
const TARGET = join(root, 'native', 'src', 'pieces');

const names = readdirSync(SOURCE)
  .filter((f) => f.endsWith('.svg'))
  .sort(byCodeUnit);
if (names.length !== 12)
  throw new Error('Expected 12 pieces, found ' + names.length);

for (const file of names) {
  const name = file.replace('.svg', '');
  const svg = readFileSync(join(SOURCE, file), 'utf8');
  const viewBox = viewBoxOf(svg, file);
  const children = convert(svg);
  // Import only the elements this piece draws.
  const used = usedComponents(children);
  writeFileSync(
    join(TARGET, name + '.tsx'),
    `// Generated from src/assets/pieces/rhosgfx/${file}.
// Do not edit by hand; run node native/scripts/generate-pieces.mjs instead.
// RhosGFX vector chess pieces, CC0. See licenses/RhosGFX-CC0.txt and
// THIRD_PARTY_NOTICES.md for provenance and credit.
import React from 'react';
import { ${['Svg', ...used].join(', ')} } from '@amazon-devices/react-native-svg';
import type { PieceProps } from './types';

export const ${name} = ({ size }: PieceProps) => (
  <Svg width={size} height={size} viewBox="${viewBox}">
${children}
  </Svg>
);
`,
  );
  console.log('wrote', name + '.tsx');
}

const letters = names.map((f) => f.replace('.svg', ''));
writeFileSync(
  join(TARGET, 'index.ts'),
  `// Generated by node native/scripts/generate-pieces.mjs. Do not edit by hand.
${letters.map((n) => `import { ${n} } from './${n}';`).join('\n')}
export type { PieceProps } from './types';

// Keyed by FEN piece letter: uppercase is White, lowercase is Black.
export const PIECES = {
${letters
  .map((n) => `  ${n.startsWith('w') ? n[1] : n[1].toLowerCase()}: ${n},`)
  .join('\n')}
} as const;
`,
);
console.log('wrote index.ts for', letters.length, 'pieces');
