// Generates React Native face components from the RhosGFX Vector Emojis sources
// in src/assets/faces/rhosgfx/: the faces of the three local opponents (#115).
//
// The conversion is the pieces', in rhosgfx-svg.mjs.
//
// Run: node native/scripts/generate-faces.mjs && npm run format
// The emitted files are checked in, and npm run format:check covers native/,
// so always format after regenerating or the gate will fail.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  byCodeUnit,
  convert,
  usedComponents,
  viewBoxOf,
} from './rhosgfx-svg.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SOURCE = join(root, 'src', 'assets', 'faces', 'rhosgfx');
const TARGET = join(root, 'native', 'src', 'faces');

// "money-mouth-face" -> "MoneyMouthFace"
const componentName = (id) =>
  id
    .split('-')
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join('');

const ids = readdirSync(SOURCE)
  .filter((f) => f.endsWith('.svg'))
  .map((f) => f.replace('.svg', ''))
  .sort(byCodeUnit);
if (ids.length !== 3) throw new Error('Expected 3 faces, found ' + ids.length);

for (const id of ids) {
  const file = id + '.svg';
  const svg = readFileSync(join(SOURCE, file), 'utf8');
  const viewBox = viewBoxOf(svg, file);
  const children = convert(svg);
  const name = componentName(id);
  writeFileSync(
    join(TARGET, name + '.tsx'),
    `// Generated from src/assets/faces/rhosgfx/${file}.
// Do not edit by hand; run node native/scripts/generate-faces.mjs instead.
// RhosGFX Vector Emojis, CC0. See licenses/RhosGFX-Emojis-CC0.txt and
// THIRD_PARTY_NOTICES.md for provenance and credit.
import React from 'react';
import { ${['Svg', ...usedComponents(children)].join(', ')} } from '@amazon-devices/react-native-svg';
import type { FaceProps } from './types';

export const ${name} = ({ size }: FaceProps) => (
  <Svg width={size} height={size} viewBox="${viewBox}">
${children}
  </Svg>
);
`,
  );
  console.log('wrote', name + '.tsx');
}

writeFileSync(
  join(TARGET, 'index.ts'),
  `// Generated by node native/scripts/generate-faces.mjs. Do not edit by hand.
${ids.map((id) => `import { ${componentName(id)} } from './${componentName(id)}';`).join('\n')}
export type { FaceProps } from './types';

// Keyed by the source's file name in src/assets/faces/rhosgfx/.
export const FACES = {
${ids.map((id) => `  '${id}': ${componentName(id)},`).join('\n')}
} as const;

export type FaceId = keyof typeof FACES;
`,
);
console.log('wrote index.ts for', ids.length, 'faces');
