// Vendors the bots' voices (#159) from fortemate/dicechess-assets at one pinned
// commit.
//
//   node scripts/vendor-voices.mjs <dicechess-assets checkout> <commit>
//
// Like vendor-sounds.mjs, files are read with `git show <commit>:<path>` and
// checked against the digests the asset repository published. The pack has one
// clip for each line of src/core/botVoice.ts, synthesized ahead of time with
// Amazon Polly and levelled to the music's loudness; the owner chose the voices
// by ear (dicechess-assets#23).
//
// Each clip keeps the text it was recorded from. test/vendoredVoices.test.ts
// fails when a line of the game has no clip, or its clip says something else, so
// a line changed in the game cannot ship with the old recording.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACK = 'polly-dicechess-bots';
const UPSTREAM = 'fortemate/dicechess-assets';
const CLIENT = 'fortemate/dicechess-tv';
const native = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const [checkout, commit] = process.argv.slice(2);
if (!checkout || !/^[0-9a-f]{40}$/.test(commit ?? ''))
  throw new Error(
    'Usage: vendor-voices.mjs <dicechess-assets checkout> <full 40-character commit>',
  );

const show = (path) =>
  execFileSync('git', ['-C', checkout, 'show', `${commit}:${path}`], {
    maxBuffer: 64 * 1024 * 1024,
  });
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');

const manifest = JSON.parse(
  show(`voices/${PACK}/manifest.json`).toString('utf8'),
);
const allowed =
  manifest.distribution === 'public' ||
  (manifest.distribution === 'project' &&
    Array.isArray(manifest.clients) &&
    manifest.clients.includes(CLIENT));
if (!allowed || !manifest.licenseFile)
  throw new Error(
    `${PACK} may not be carried by ${CLIENT} (license ${manifest.license}, distribution ${manifest.distribution})`,
  );
const published = JSON.parse(
  show(`voices/${PACK}/checksums.json`).toString('utf8'),
);

const root = join(native, 'voices');
rmSync(root, { recursive: true, force: true });
mkdirSync(join(root, PACK), { recursive: true });
const files = {};
const copy = (path) => {
  const bytes = show(`voices/${PACK}/${path}`);
  const digest = sha256(bytes);
  if (published[path] !== digest)
    throw new Error(
      `${PACK}/${path} does not match the digest ${UPSTREAM} published at ${commit}`,
    );
  const name = path.split('/').pop();
  writeFileSync(join(root, PACK, name), bytes);
  files[name] = digest;
  return { file: `${PACK}/${name}`, sha256: digest };
};

copy('manifest.json');
copy(manifest.licenseFile);
const lines = {};
// Code-unit order, the same on every machine; localeCompare is not.
const ids = Object.keys(manifest.lines ?? {}).sort(
  (a, b) => Number(a > b) - Number(a < b),
);
if (ids.length === 0)
  throw new Error(`${PACK} has no pack lines at ${commit}: only an audition?`);
for (const id of ids) {
  const line = manifest.lines[id];
  const { file, sha256: digest } = copy(line.export);
  if (digest !== line.sha256)
    throw new Error(`${id} does not match its record in the manifest`);
  lines[id] = {
    bot: line.bot,
    event: line.event,
    text: line.text,
    voice: line.voice,
    file,
    sha256: digest,
    seconds: line.durationSeconds,
  };
}

const catalogue = {
  upstream: UPSTREAM,
  commit,
  pack: PACK,
  title: manifest.title,
  license: manifest.license,
  licenseFile: manifest.licenseFile,
  distribution: manifest.distribution,
  clients: manifest.clients ?? null,
  attributionRequired: manifest.attributionRequired,
  generator: manifest.generator?.tool ?? null,
  // The commit of this repository whose lines the pack was recorded from.
  texts: manifest.pack?.texts ?? null,
  lines,
  // Every file vendored for the pack, with its digest.
  files,
};
writeFileSync(
  join(root, 'voices.json'),
  JSON.stringify(catalogue, null, 2) + '\n',
);

// The app reads this at run time. It is generated, rather than importing the
// catalogue, so neither Metro nor the test runner has to be taught JSON modules.
const body = Object.entries(lines)
  .map(
    ([id, { file, seconds, text }]) =>
      `  ${id}: { file: ${JSON.stringify(file)}, seconds: ${seconds}, text: ${JSON.stringify(text)} },`,
  )
  .join('\n');
writeFileSync(
  join(native, 'src/voiceFiles.ts'),
  `// Generated by scripts/vendor-voices.mjs from voices/voices.json. Do not edit.
//
// The clip of each bot line, by the line's id in src/core/botVoice.ts: its file
// relative to the voices directory the build copies it into, how long it plays,
// and the text it was recorded from.
export type VoiceClip = {
  readonly file: string;
  readonly seconds: number;
  readonly text: string;
};

export const VOICE_FILES: Readonly<Record<string, VoiceClip>> = {
${body}
};
`,
);

// Formatted like the rest of the source, so the format check passes and a
// re-run leaves no diff.
execFileSync(
  'npx',
  ['prettier', '--write', join(native, 'src/voiceFiles.ts')],
  { cwd: native, stdio: 'ignore' },
);

console.log(
  `voices: ${ids.length} lines from ${PACK} at ${commit.slice(0, 7)} -> native/voices/`,
);
