// Vendors the game's sounds from fortemate/dicechess-assets at one pinned commit.
//
//   node scripts/vendor-sounds.mjs <path-to-dicechess-assets-checkout> <commit>
//
// The asset repository's consumption rules ask a client to pin a full commit and
// never build against a moving branch, to keep each pack's licence and manifest
// beside its files, and to record where everything came from. This does all
// three. Files are read with `git show <commit>:<path>`, so the state of the
// checkout's working tree does not matter, and every file is checked against the
// digest the asset repository itself published for it before it is written.
//
// CUES below is the one place this application decides which sound means what.
// Each cue names a pack and one of that pack's events; the MP3 files the event
// lists are what the cue may play, one picked at random when there are several.
// The choices were made by ear by the owner (dicechess-assets#8).
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CUES = {
  dice_roll: ['kenney-casino-audio', 'dice_roll'],
  turn_handoff: ['kenney-casino-audio', 'turn_handoff'],
  piece_move: ['jdsherbert-tabletop', 'piece_move'],
  // Castling is a move, and it spends one; it sounds like one.
  castle: ['jdsherbert-tabletop', 'piece_move'],
  piece_capture: ['jdsherbert-tabletop', 'piece_capture'],
  promotion: ['kenney-interface-sounds', 'promotion'],
  game_win: ['kenney-music-jingles', 'game_win'],
  game_loss: ['kenney-music-jingles', 'game_loss'],
  game_draw: ['kenney-music-jingles', 'game_draw'],
};

const UPSTREAM = 'fortemate/dicechess-assets';
const native = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const [checkout, commit] = process.argv.slice(2);
if (!checkout || !/^[0-9a-f]{40}$/.test(commit ?? ''))
  throw new Error(
    'Usage: vendor-sounds.mjs <dicechess-assets checkout> <full 40-character commit>',
  );

const show = (path) =>
  execFileSync('git', ['-C', checkout, 'show', `${commit}:${path}`], {
    maxBuffer: 64 * 1024 * 1024,
  });
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');

const packs = {};
const cues = {};
for (const [cue, [packId, event]] of Object.entries(CUES)) {
  const manifest = JSON.parse(
    show(`sounds/${packId}/manifest.json`).toString('utf8'),
  );
  const exports = (manifest.events?.[event] ?? []).filter((path) =>
    path.endsWith('.mp3'),
  );
  if (exports.length === 0)
    throw new Error(
      `${packId} has no MP3 export for event ${event} at ${commit}`,
    );
  packs[packId] ??= { manifest, exports: new Set() };
  for (const path of exports) packs[packId].exports.add(path);
  cues[cue] = exports.map((path) => `${packId}/${path.split('/').pop()}`);
}

const root = join(native, 'sounds');
const lock = { upstream: UPSTREAM, commit, packs: {}, cues };
for (const [packId, { manifest, exports }] of Object.entries(packs)) {
  const published = JSON.parse(
    show(`sounds/${packId}/checksums.json`).toString('utf8'),
  );
  const dir = join(root, packId);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const files = {};
  for (const path of [
    'manifest.json',
    manifest.licenseFile,
    // Code-unit order, the same on every machine; localeCompare is not.
    ...[...exports].sort((a, b) => Number(a > b) - Number(a < b)),
  ]) {
    const bytes = show(`sounds/${packId}/${path}`);
    const digest = sha256(bytes);
    if (published[path] !== digest)
      throw new Error(
        `${packId}/${path} does not match the digest ${UPSTREAM} published at ${commit}`,
      );
    const name = path.split('/').pop();
    writeFileSync(join(dir, name), bytes);
    files[name] = { from: `sounds/${packId}/${path}`, sha256: digest };
  }
  lock.packs[packId] = {
    version: manifest.version,
    license: manifest.license,
    attribution: manifest.attribution,
    attributionRequired: manifest.attributionRequired,
    files,
  };
}
writeFileSync(
  join(root, 'sounds.lock.json'),
  JSON.stringify(lock, null, 2) + '\n',
);

// The app reads this at run time. It is generated, rather than importing the
// lock, so neither Metro nor the test runner has to be taught JSON modules.
const quote = (file) => `'${file}'`;
const body = Object.entries(cues)
  .map(([cue, list]) => `  ${cue}: [${list.map(quote).join(', ')}],`)
  .join('\n');
writeFileSync(
  join(native, 'src/cueFiles.ts'),
  `// Generated by scripts/vendor-sounds.mjs from sounds/sounds.lock.json. Do not edit.
//
// The vendored files each cue may play, relative to the sfx directory the build
// copies them into. Where there are several, one is picked at random.
import type { Cue } from '../../src/core/cues';

export const CUE_FILES: Readonly<Record<Cue, readonly string[]>> = {
${body}
};
`,
);

// Formatted like the rest of the source, so the format check passes and a
// re-run leaves no diff.
execFileSync('npx', ['prettier', '--write', join(native, 'src/cueFiles.ts')], {
  cwd: native,
  stdio: 'ignore',
});

const count = Object.values(lock.packs).reduce(
  (n, p) => n + Object.keys(p.files).length,
  0,
);
console.log(
  `vendored ${count} files from ${UPSTREAM}@${commit.slice(0, 7)} for ${Object.keys(cues).length} cues`,
);
