// Generated by node native/scripts/generate-faces.mjs. Do not edit by hand.
import { MoneyMouthFace } from './MoneyMouthFace';
import { SmilingFaceWithHorns } from './SmilingFaceWithHorns';
import { ZanyFace } from './ZanyFace';
export type { FaceProps } from './types';

// Keyed by the source's file name in src/assets/faces/rhosgfx/.
export const FACES = {
  'money-mouth-face': MoneyMouthFace,
  'smiling-face-with-horns': SmilingFaceWithHorns,
  'zany-face': ZanyFace,
} as const;

export type FaceId = keyof typeof FACES;
