// Generated by node native/scripts/generate-pieces.mjs. Do not edit by hand.
import { bB } from './bB';
import { bK } from './bK';
import { bN } from './bN';
import { bP } from './bP';
import { bQ } from './bQ';
import { bR } from './bR';
import { wB } from './wB';
import { wK } from './wK';
import { wN } from './wN';
import { wP } from './wP';
import { wQ } from './wQ';
import { wR } from './wR';
export type { PieceProps } from './types';

// Keyed by FEN piece letter: uppercase is White, lowercase is Black.
export const PIECES = {
  b: bB,
  k: bK,
  n: bN,
  p: bP,
  q: bQ,
  r: bR,
  B: wB,
  K: wK,
  N: wN,
  P: wP,
  Q: wQ,
  R: wR,
} as const;
