// Lint for the Vega application: typescript-eslint's recommended rules, React's
// hooks rules, and Amazon's Vega rules from @amazon-devices/eslint-plugin-kepler.
//
// ESLint stays on major 9. The Vega plugin (0.1.15) still calls
// context.getSourceCode(), which ESLint 10 removed, and crashes there; Dependabot
// holds the major back for the same reason. The plugin ships eslintrc presets
// only, so its rules are spread into flat config by hand below.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import vega from '@amazon-devices/eslint-plugin-kepler';
import * as jsonc from 'jsonc-eslint-parser';
import globals from 'globals';

export default tseslint.config(
  // `assets/` and `build/` are generated by the build; `sounds/` is vendored.
  { ignores: ['assets/', 'build/', 'sounds/'] },
  js.configs.recommended,
  tseslint.configs.recommended,
  reactHooks.configs.flat.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { '@amazon-devices/kepler': vega },
    rules: {
      ...vega.configs.kepler.rules,
      // Informational by its own account ("This is not an error"): it flags
      // every import of a system-distributed library until the developer has
      // read about them. The version rule on package.json below is the one that
      // acts on it.
      '@amazon-devices/kepler/sdl-package-version-check-imports': 'off',
    },
  },
  {
    // Amazon's rule for system-distributed libraries — the ones the device
    // provides rather than the package: patch ranges only, neither exact pins
    // nor minor ranges.
    files: ['package.json'],
    languageOptions: { parser: jsonc },
    plugins: { '@amazon-devices/kepler': vega },
    rules: {
      '@amazon-devices/kepler/sdl-package-version-check': [
        'error',
        { semverGuidance: 'auto' },
      ],
    },
  },
  {
    // Build configuration, scripts and the test loader run in Node.
    files: ['**/*.{js,mjs}'],
    languageOptions: { globals: globals.node },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
);
