// Generated by native/scripts/vendor-voices.mjs from native/voices/events.json.
// Do not edit: change events.json in dicechess-assets and vendor it again.
//
// How often the Hot Seat host speaks (#202): the importance tier and priority of
// each host event, and the pacing every Dice Chess client follows, so the TV,
// the web and the phone sound alike. A lower priority number wins when events
// meet in one step. docs/CHARACTERS.md in dicechess-assets explains the tiers.
export type Tier = 'always' | 'notable' | 'frequent';

export type HostEvent =
  | 'white_wins'
  | 'black_wins'
  | 'win'
  | 'draw'
  | 'intro'
  | 'again'
  | 'handoff'
  | 'en_passant'
  | 'castling'
  | 'promotion'
  | 'capture_queen'
  | 'capture_heavy'
  | 'empty_roll'
  | 'capture';

export type HostPacing = {
  readonly alwaysPerEvent: number;
  readonly notableCooldownTurns: number;
  readonly notablePerEvent: number;
  readonly frequentCooldownTurns: number;
  readonly frequentChance: number;
  readonly repeatDecay: number;
  readonly silenceBreakerTurns: number;
};

export const HOST_PACING: HostPacing = {
  alwaysPerEvent: 2,
  notableCooldownTurns: 2,
  notablePerEvent: 3,
  frequentCooldownTurns: 6,
  frequentChance: 0.7,
  repeatDecay: 0.5,
  silenceBreakerTurns: 8,
};

export const HOST_EVENTS: Readonly<
  Record<HostEvent, { readonly tier: Tier; readonly priority: number }>
> = {
  white_wins: { tier: 'always', priority: 1 },
  black_wins: { tier: 'always', priority: 1 },
  win: { tier: 'always', priority: 1 },
  draw: { tier: 'always', priority: 1 },
  intro: { tier: 'always', priority: 2 },
  again: { tier: 'always', priority: 2 },
  handoff: { tier: 'always', priority: 3 },
  en_passant: { tier: 'always', priority: 4 },
  castling: { tier: 'always', priority: 5 },
  promotion: { tier: 'always', priority: 6 },
  capture_queen: { tier: 'always', priority: 7 },
  capture_heavy: { tier: 'notable', priority: 8 },
  empty_roll: { tier: 'notable', priority: 10 },
  capture: { tier: 'frequent', priority: 11 },
};
