// Generated by scripts/vendor-sounds.mjs from sounds/sounds.lock.json. Do not edit.
//
// The vendored files each cue may play, relative to the sfx directory the build
// copies them into. Where there are several, one is picked at random.
import type { Cue } from '../../src/core/cues';

export const CUE_FILES: Readonly<Record<Cue, readonly string[]>> = {
  dice_roll: [
    'kenney-casino-audio/dice_throw_1.mp3',
    'kenney-casino-audio/dice_throw_2.mp3',
    'kenney-casino-audio/dice_throw_3.mp3',
  ],
  turn_handoff: ['kenney-casino-audio/dice_grab_2.mp3'],
  piece_move: [
    'jdsherbert-tabletop/piece_move_1.mp3',
    'jdsherbert-tabletop/piece_move_2.mp3',
  ],
  castle: [
    'jdsherbert-tabletop/piece_move_1.mp3',
    'jdsherbert-tabletop/piece_move_2.mp3',
  ],
  piece_capture: [
    'jdsherbert-tabletop/piece_impact_1.mp3',
    'jdsherbert-tabletop/piece_impact_2.mp3',
  ],
  promotion: ['kenney-interface-sounds/maximize_006.mp3'],
  no_move: ['kenney-interface-sounds/glass_004.mp3'],
  game_win: ['kenney-music-jingles/pizzicato_02.mp3'],
  game_loss: ['kenney-music-jingles/pizzicato_01.mp3'],
  game_draw: ['kenney-music-jingles/pizzicato_03.mp3'],
};
