// Generated by scripts/vendor-voices.mjs from voices/voices.json. Do not edit.
//
// The clip of each bot line, by the line's id in src/core/botVoice.ts: its file
// relative to the voices directory the build copies it into, how long it plays,
// and the text it was recorded from.
export type VoiceClip = {
  readonly file: string;
  readonly seconds: number;
  readonly text: string;
};

export const VOICE_FILES: Readonly<Record<string, VoiceClip>> = {
  grabby_capture_1: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_1.mp3',
    seconds: 3.36,
    text: "Mine! I'll take that, thank you.",
  },
  grabby_capture_2: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_2.mp3',
    seconds: 3.44,
    text: 'Another piece added to my private collection.',
  },
  grabby_capture_3: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_3.mp3',
    seconds: 4.72,
    text: "Yoink! You shouldn't leave valuables lying around.",
  },
  grabby_capture_heavy_1: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_heavy_1.mp3',
    seconds: 4.64,
    text: 'Jackpot! That prize piece is mine!',
  },
  grabby_capture_heavy_2: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_heavy_2.mp3',
    seconds: 5.28,
    text: 'Exquisite loot! A crown jewel for my hoard!',
  },
  grabby_capture_heavy_3: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_heavy_3.mp3',
    seconds: 4.56,
    text: 'The bigger the piece, the sweeter the profit!',
  },
  grabby_empty_roll_1: {
    file: 'elevenlabs-dicechess-bots/grabby_empty_roll_1.mp3',
    seconds: 3.52,
    text: 'No moves?! But I wanted to take something!',
  },
  grabby_empty_roll_2: {
    file: 'elevenlabs-dicechess-bots/grabby_empty_roll_2.mp3',
    seconds: 5.28,
    text: 'A waste of a roll! No loot for my vault this turn.',
  },
  grabby_empty_roll_3: {
    file: 'elevenlabs-dicechess-bots/grabby_empty_roll_3.mp3',
    seconds: 4.4,
    text: 'Empty roll! You got lucky... for now.',
  },
  grabby_intro_1: {
    file: 'elevenlabs-dicechess-bots/grabby_intro_1.mp3',
    seconds: 4.08,
    text: 'Everything on this board belongs in my collection.',
  },
  grabby_intro_2: {
    file: 'elevenlabs-dicechess-bots/grabby_intro_2.mp3',
    seconds: 4.64,
    text: "Don't get attached to your pieces. I'm taking them all.",
  },
  grabby_intro_3: {
    file: 'elevenlabs-dicechess-bots/grabby_intro_3.mp3',
    seconds: 4.48,
    text: 'A fresh board! So many shiny pieces to hoard.',
  },
  grabby_loss_1: {
    file: 'elevenlabs-dicechess-bots/grabby_loss_1.mp3',
    seconds: 5.76,
    text: 'No! My glorious collection! How dare you?!',
  },
  grabby_loss_2: {
    file: 'elevenlabs-dicechess-bots/grabby_loss_2.mp3',
    seconds: 3.92,
    text: 'Unacceptable! You plundered my king?!',
  },
  grabby_loss_3: {
    file: 'elevenlabs-dicechess-bots/grabby_loss_3.mp3',
    seconds: 6.08,
    text: 'Defeated?! My treasures... slipping away...',
  },
  grabby_threat_1: {
    file: 'elevenlabs-dicechess-bots/grabby_threat_1.mp3',
    seconds: 3.6,
    text: 'Your king would look lovely in my vault.',
  },
  grabby_threat_2: {
    file: 'elevenlabs-dicechess-bots/grabby_threat_2.mp3',
    seconds: 3.12,
    text: 'One good roll and your king is mine!',
  },
  grabby_threat_3: {
    file: 'elevenlabs-dicechess-bots/grabby_threat_3.mp3',
    seconds: 4.24,
    text: 'I spy your king. Very collectible!',
  },
  grabby_win_1: {
    file: 'elevenlabs-dicechess-bots/grabby_win_1.mp3',
    seconds: 6,
    text: 'Victory and total plunder! What a splendid haul!',
  },
  grabby_win_2: {
    file: 'elevenlabs-dicechess-bots/grabby_win_2.mp3',
    seconds: 4.32,
    text: 'All your squares and treasures are mine!',
  },
  grabby_win_3: {
    file: 'elevenlabs-dicechess-bots/grabby_win_3.mp3',
    seconds: 4.08,
    text: 'Greed is good, but winning is priceless!',
  },
  rampage_capture_1: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_1.mp3',
    seconds: 4.24,
    text: 'Obliterated! One less obstacle in my path.',
  },
  rampage_capture_2: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_2.mp3',
    seconds: 3.92,
    text: 'Cut down! Your ranks crumble before me.',
  },
  rampage_capture_3: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_3.mp3',
    seconds: 3.36,
    text: 'Pathetic defense! Smashed aside!',
  },
  rampage_capture_heavy_1: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_heavy_1.mp3',
    seconds: 4.16,
    text: 'Crushed! Your mightiest defender falls into dust!',
  },
  rampage_capture_heavy_2: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_heavy_2.mp3',
    seconds: 5.52,
    text: 'Devastating strike! You cannot withstand my assault!',
  },
  rampage_capture_heavy_3: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_heavy_3.mp3',
    seconds: 4.24,
    text: 'Your high command is broken! Smashed to pieces!',
  },
  rampage_empty_roll_1: {
    file: 'elevenlabs-dicechess-bots/rampage_empty_roll_1.mp3',
    seconds: 4.72,
    text: 'The dice stall my fury. Savor your brief respite.',
  },
  rampage_empty_roll_2: {
    file: 'elevenlabs-dicechess-bots/rampage_empty_roll_2.mp3',
    seconds: 4.88,
    text: 'No targets?! Unacceptable! Next turn you fall.',
  },
  rampage_empty_roll_3: {
    file: 'elevenlabs-dicechess-bots/rampage_empty_roll_3.mp3',
    seconds: 3.36,
    text: 'A momentary pause before the storm resumes.',
  },
  rampage_intro_1: {
    file: 'elevenlabs-dicechess-bots/rampage_intro_1.mp3',
    seconds: 4.56,
    text: 'Step forward. Your king will not survive this day.',
  },
  rampage_intro_2: {
    file: 'elevenlabs-dicechess-bots/rampage_intro_2.mp3',
    seconds: 4.72,
    text: 'No mercy. No retreat. Let the battle begin.',
  },
  rampage_intro_3: {
    file: 'elevenlabs-dicechess-bots/rampage_intro_3.mp3',
    seconds: 4.24,
    text: 'Prepare yourself! I strike without hesitation.',
  },
  rampage_loss_1: {
    file: 'elevenlabs-dicechess-bots/rampage_loss_1.mp3',
    seconds: 3.68,
    text: 'Impossible! How could my onslaught fail?!',
  },
  rampage_loss_2: {
    file: 'elevenlabs-dicechess-bots/rampage_loss_2.mp3',
    seconds: 5.2,
    text: 'You fought fiercely... I acknowledge your triumph.',
  },
  rampage_loss_3: {
    file: 'elevenlabs-dicechess-bots/rampage_loss_3.mp3',
    seconds: 4.72,
    text: 'Downed, but not broken! We will battle again!',
  },
  rampage_threat_1: {
    file: 'elevenlabs-dicechess-bots/rampage_threat_1.mp3',
    seconds: 2.56,
    text: 'Your king is in my sights!',
  },
  rampage_threat_2: {
    file: 'elevenlabs-dicechess-bots/rampage_threat_2.mp3',
    seconds: 3.2,
    text: 'The right roll, and your king falls!',
  },
  rampage_threat_3: {
    file: 'elevenlabs-dicechess-bots/rampage_threat_3.mp3',
    seconds: 4.16,
    text: "I can smell your king's fear!",
  },
  rampage_win_1: {
    file: 'elevenlabs-dicechess-bots/rampage_win_1.mp3',
    seconds: 5.04,
    text: 'Total annihilation! Kneel before the conqueror!',
  },
  rampage_win_2: {
    file: 'elevenlabs-dicechess-bots/rampage_win_2.mp3',
    seconds: 4.64,
    text: 'Your army is crushed beneath my heel!',
  },
  rampage_win_3: {
    file: 'elevenlabs-dicechess-bots/rampage_win_3.mp3',
    seconds: 4.4,
    text: 'Victory was inevitable! You were completely outmatched!',
  },
  rolly_capture_1: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_1.mp3',
    seconds: 2.88,
    text: 'Boop! Mine now!',
  },
  rolly_capture_2: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_2.mp3',
    seconds: 3.12,
    text: 'Got one! Every little piece counts!',
  },
  rolly_capture_3: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_3.mp3',
    seconds: 2.8,
    text: 'Snack time for my pieces!',
  },
  rolly_capture_heavy_1: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_heavy_1.mp3',
    seconds: 4.48,
    text: 'Whoa! Did I really just grab that big piece?!',
  },
  rolly_capture_heavy_2: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_heavy_2.mp3',
    seconds: 4.72,
    text: 'Look what I found! Down goes a heavy hitter!',
  },
  rolly_capture_heavy_3: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_heavy_3.mp3',
    seconds: 3.84,
    text: 'Yay! That was a huge capture!',
  },
  rolly_empty_roll_1: {
    file: 'elevenlabs-dicechess-bots/rolly_empty_roll_1.mp3',
    seconds: 4.4,
    text: 'Oops, nowhere to go! Your turn!',
  },
  rolly_empty_roll_2: {
    file: 'elevenlabs-dicechess-bots/rolly_empty_roll_2.mp3',
    seconds: 4.08,
    text: "Nothing to move? That's dice for you!",
  },
  rolly_empty_roll_3: {
    file: 'elevenlabs-dicechess-bots/rolly_empty_roll_3.mp3',
    seconds: 4.64,
    text: 'A blank roll! Well, that was silly!',
  },
  rolly_intro_1: {
    file: 'elevenlabs-dicechess-bots/rolly_intro_1.mp3',
    seconds: 3.04,
    text: "Hey! Let's roll and see what happens!",
  },
  rolly_intro_2: {
    file: 'elevenlabs-dicechess-bots/rolly_intro_2.mp3',
    seconds: 4.48,
    text: "Dice ready, board ready! Let's have fun!",
  },
  rolly_intro_3: {
    file: 'elevenlabs-dicechess-bots/rolly_intro_3.mp3',
    seconds: 4.24,
    text: "I love rolling dice! Hope they're friendly today!",
  },
  rolly_loss_1: {
    file: 'elevenlabs-dicechess-bots/rolly_loss_1.mp3',
    seconds: 4.8,
    text: 'Aww, good game! You got me fair and square!',
  },
  rolly_loss_2: {
    file: 'elevenlabs-dicechess-bots/rolly_loss_2.mp3',
    seconds: 4.64,
    text: 'My king tripped! Nice catch!',
  },
  rolly_loss_3: {
    file: 'elevenlabs-dicechess-bots/rolly_loss_3.mp3',
    seconds: 4.32,
    text: "You're too good! Let's play another round!",
  },
  rolly_threat_1: {
    file: 'elevenlabs-dicechess-bots/rolly_threat_1.mp3',
    seconds: 3.84,
    text: 'Ooh! Your king is right in my path!',
  },
  rolly_threat_2: {
    file: 'elevenlabs-dicechess-bots/rolly_threat_2.mp3',
    seconds: 4.4,
    text: 'One lucky roll and your king goes boop!',
  },
  rolly_threat_3: {
    file: 'elevenlabs-dicechess-bots/rolly_threat_3.mp3',
    seconds: 2.88,
    text: 'Psst... your king might want to hide!',
  },
  rolly_win_1: {
    file: 'elevenlabs-dicechess-bots/rolly_win_1.mp3',
    seconds: 3.28,
    text: 'Yay, I won! Can we roll again?!',
  },
  rolly_win_2: {
    file: 'elevenlabs-dicechess-bots/rolly_win_2.mp3',
    seconds: 4.8,
    text: 'Woohoo! The dice were super friendly today!',
  },
  rolly_win_3: {
    file: 'elevenlabs-dicechess-bots/rolly_win_3.mp3',
    seconds: 4,
    text: 'High five! That was so much fun!',
  },
};
