// Generated by scripts/vendor-voices.mjs from voices/voices.json. Do not edit.
//
// The clip of each line, a bot's or the Hot Seat host's, by the line's id in
// src/core/botVoice.ts or src/core/hostVoice.ts: its file relative to the
// voices directory the build copies it into, how long it plays, and the text it
// was recorded from.
export type VoiceClip = {
  readonly file: string;
  readonly seconds: number;
  readonly text: string;
};

export const VOICE_FILES: Readonly<Record<string, VoiceClip>> = {
  grabby_capture_1: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_1.mp3',
    seconds: 3.36,
    text: "Mine! I'll take that, thank you.",
  },
  grabby_capture_2: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_2.mp3',
    seconds: 3.44,
    text: 'Another piece added to my private collection.',
  },
  grabby_capture_3: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_3.mp3',
    seconds: 4.72,
    text: "Yoink! You shouldn't leave valuables lying around.",
  },
  grabby_capture_heavy_1: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_heavy_1.mp3',
    seconds: 4.64,
    text: 'Jackpot! That prize piece is mine!',
  },
  grabby_capture_heavy_2: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_heavy_2.mp3',
    seconds: 5.28,
    text: 'Exquisite loot! A crown jewel for my hoard!',
  },
  grabby_capture_heavy_3: {
    file: 'elevenlabs-dicechess-bots/grabby_capture_heavy_3.mp3',
    seconds: 4.56,
    text: 'The bigger the piece, the sweeter the profit!',
  },
  grabby_empty_roll_1: {
    file: 'elevenlabs-dicechess-bots/grabby_empty_roll_1.mp3',
    seconds: 3.52,
    text: 'No moves?! But I wanted to take something!',
  },
  grabby_empty_roll_2: {
    file: 'elevenlabs-dicechess-bots/grabby_empty_roll_2.mp3',
    seconds: 5.28,
    text: 'A waste of a roll! No loot for my vault this turn.',
  },
  grabby_empty_roll_3: {
    file: 'elevenlabs-dicechess-bots/grabby_empty_roll_3.mp3',
    seconds: 4.4,
    text: 'Empty roll! You got lucky... for now.',
  },
  grabby_intro_1: {
    file: 'elevenlabs-dicechess-bots/grabby_intro_1.mp3',
    seconds: 4.08,
    text: 'Everything on this board belongs in my collection.',
  },
  grabby_intro_2: {
    file: 'elevenlabs-dicechess-bots/grabby_intro_2.mp3',
    seconds: 4.64,
    text: "Don't get attached to your pieces. I'm taking them all.",
  },
  grabby_intro_3: {
    file: 'elevenlabs-dicechess-bots/grabby_intro_3.mp3',
    seconds: 4.48,
    text: 'A fresh board! So many shiny pieces to hoard.',
  },
  grabby_loss_1: {
    file: 'elevenlabs-dicechess-bots/grabby_loss_1.mp3',
    seconds: 5.76,
    text: 'No! My glorious collection! How dare you?!',
  },
  grabby_loss_2: {
    file: 'elevenlabs-dicechess-bots/grabby_loss_2.mp3',
    seconds: 3.92,
    text: 'Unacceptable! You plundered my king?!',
  },
  grabby_loss_3: {
    file: 'elevenlabs-dicechess-bots/grabby_loss_3.mp3',
    seconds: 6.08,
    text: 'Defeated?! My treasures... slipping away...',
  },
  grabby_threat_1: {
    file: 'elevenlabs-dicechess-bots/grabby_threat_1.mp3',
    seconds: 3.6,
    text: 'Your king would look lovely in my vault.',
  },
  grabby_threat_2: {
    file: 'elevenlabs-dicechess-bots/grabby_threat_2.mp3',
    seconds: 3.12,
    text: 'One good roll and your king is mine!',
  },
  grabby_threat_3: {
    file: 'elevenlabs-dicechess-bots/grabby_threat_3.mp3',
    seconds: 4.24,
    text: 'I spy your king. Very collectible!',
  },
  grabby_win_1: {
    file: 'elevenlabs-dicechess-bots/grabby_win_1.mp3',
    seconds: 6,
    text: 'Victory and total plunder! What a splendid haul!',
  },
  grabby_win_2: {
    file: 'elevenlabs-dicechess-bots/grabby_win_2.mp3',
    seconds: 4.32,
    text: 'All your squares and treasures are mine!',
  },
  grabby_win_3: {
    file: 'elevenlabs-dicechess-bots/grabby_win_3.mp3',
    seconds: 4.08,
    text: 'Greed is good, but winning is priceless!',
  },
  host_again_1: {
    file: 'elevenlabs-dicechess-host/host_again_1.mp3',
    seconds: 4.24,
    text: 'Another game? Yay, more cheering for me!',
  },
  host_again_2: {
    file: 'elevenlabs-dicechess-host/host_again_2.mp3',
    seconds: 3.36,
    text: "New game, new luck! Who's ready?",
  },
  host_again_3: {
    file: 'elevenlabs-dicechess-host/host_again_3.mp3',
    seconds: 4.4,
    text: 'Back for more? The dice are all warmed up!',
  },
  host_black_wins_1: {
    file: 'elevenlabs-dicechess-host/host_black_wins_1.mp3',
    seconds: 3.68,
    text: 'Black takes the game! Well played, both!',
  },
  host_black_wins_2: {
    file: 'elevenlabs-dicechess-host/host_black_wins_2.mp3',
    seconds: 4.16,
    text: "It's Black's game! What a match, you two!",
  },
  host_black_wins_3: {
    file: 'elevenlabs-dicechess-host/host_black_wins_3.mp3',
    seconds: 3.44,
    text: 'Three cheers for Black, and for White too!',
  },
  host_capture_1: {
    file: 'elevenlabs-dicechess-host/host_capture_1.mp3',
    seconds: 3.04,
    text: 'Pop! One piece hops off the board!',
  },
  host_capture_2: {
    file: 'elevenlabs-dicechess-host/host_capture_2.mp3',
    seconds: 3.68,
    text: 'Oho! The plot thickens!',
  },
  host_capture_3: {
    file: 'elevenlabs-dicechess-host/host_capture_3.mp3',
    seconds: 4.16,
    text: 'A capture! A little more room on the board!',
  },
  host_capture_4: {
    file: 'elevenlabs-dicechess-host/host_capture_4.mp3',
    seconds: 3.92,
    text: 'And that piece is off for a little rest!',
  },
  host_capture_heavy_1: {
    file: 'elevenlabs-dicechess-host/host_capture_heavy_1.mp3',
    seconds: 4.4,
    text: 'Wowee! The whole board felt that one!',
  },
  host_capture_heavy_2: {
    file: 'elevenlabs-dicechess-host/host_capture_heavy_2.mp3',
    seconds: 3.84,
    text: 'Kaboom! A mighty piece leaves the board!',
  },
  host_capture_heavy_3: {
    file: 'elevenlabs-dicechess-host/host_capture_heavy_3.mp3',
    seconds: 4.56,
    text: 'Timber! What a tumble!',
  },
  host_capture_heavy_4: {
    file: 'elevenlabs-dicechess-host/host_capture_heavy_4.mp3',
    seconds: 4.48,
    text: 'Big, big moment! Somebody pinch me!',
  },
  host_capture_heavy_5: {
    file: 'elevenlabs-dicechess-host/host_capture_heavy_5.mp3',
    seconds: 3.92,
    text: 'Oh my! Hold on to your seats, you two!',
  },
  host_capture_queen_1: {
    file: 'elevenlabs-dicechess-host/host_capture_queen_1.mp3',
    seconds: 4.08,
    text: 'A queen is taken! Deep breaths, you two!',
  },
  host_capture_queen_2: {
    file: 'elevenlabs-dicechess-host/host_capture_queen_2.mp3',
    seconds: 3.68,
    text: 'Oh, the queen! My heart just did a flip!',
  },
  host_capture_queen_3: {
    file: 'elevenlabs-dicechess-host/host_capture_queen_3.mp3',
    seconds: 3.28,
    text: 'Ooh... there goes a queen!',
  },
  host_capture_queen_4: {
    file: 'elevenlabs-dicechess-host/host_capture_queen_4.mp3',
    seconds: 5.04,
    text: 'Queen down! My microphone is shaking!',
  },
  host_draw_1: {
    file: 'elevenlabs-dicechess-host/host_draw_1.mp3',
    seconds: 5.6,
    text: 'A draw! Nobody wins, and everybody wins!',
  },
  host_draw_2: {
    file: 'elevenlabs-dicechess-host/host_draw_2.mp3',
    seconds: 3.84,
    text: "It's a draw! You two are perfectly matched!",
  },
  host_draw_3: {
    file: 'elevenlabs-dicechess-host/host_draw_3.mp3',
    seconds: 4.96,
    text: 'All even! Shake hands, both of you!',
  },
  host_empty_roll_1: {
    file: 'elevenlabs-dicechess-host/host_empty_roll_1.mp3',
    seconds: 4.4,
    text: 'The dice said no! Pass it along!',
  },
  host_empty_roll_2: {
    file: 'elevenlabs-dicechess-host/host_empty_roll_2.mp3',
    seconds: 5.76,
    text: 'Aww, bad luck! Those dice are so cheeky!',
  },
  host_empty_roll_3: {
    file: 'elevenlabs-dicechess-host/host_empty_roll_3.mp3',
    seconds: 5.04,
    text: 'Oh no, the dice took a nap! Next turn!',
  },
  host_empty_roll_4: {
    file: 'elevenlabs-dicechess-host/host_empty_roll_4.mp3',
    seconds: 4.8,
    text: 'Uh-oh! The dice are playing tricks on us!',
  },
  host_en_passant_1: {
    file: 'elevenlabs-dicechess-host/host_en_passant_1.mp3',
    seconds: 4,
    text: 'En passant! A rare sideways capture!',
  },
  host_en_passant_2: {
    file: 'elevenlabs-dicechess-host/host_en_passant_2.mp3',
    seconds: 3.44,
    text: 'Did you see that? A pawn caught in passing!',
  },
  host_en_passant_3: {
    file: 'elevenlabs-dicechess-host/host_en_passant_3.mp3',
    seconds: 3.6,
    text: "Psst... that's called en passant!",
  },
  host_handoff_1: {
    file: 'elevenlabs-dicechess-host/host_handoff_1.mp3',
    seconds: 3.2,
    text: "Now pass the remote over! Black's turn!",
  },
  host_handoff_2: {
    file: 'elevenlabs-dicechess-host/host_handoff_2.mp3',
    seconds: 3.36,
    text: 'After every turn, the remote changes hands!',
  },
  host_handoff_3: {
    file: 'elevenlabs-dicechess-host/host_handoff_3.mp3',
    seconds: 4.8,
    text: 'Remote swap time! Black, roll away!',
  },
  host_intro_1: {
    file: 'elevenlabs-dicechess-host/host_intro_1.mp3',
    seconds: 3.04,
    text: "You two play, and I'll do the cheering!",
  },
  host_intro_2: {
    file: 'elevenlabs-dicechess-host/host_intro_2.mp3',
    seconds: 4.08,
    text: "No dice for me! I'm just the host!",
  },
  host_intro_3: {
    file: 'elevenlabs-dicechess-host/host_intro_3.mp3',
    seconds: 3.76,
    text: 'Welcome, both of you! White rolls first!',
  },
  host_intro_4: {
    file: 'elevenlabs-dicechess-host/host_intro_4.mp3',
    seconds: 4.88,
    text: 'One board, two players, three dice! Go!',
  },
  host_intro_5: {
    file: 'elevenlabs-dicechess-host/host_intro_5.mp3',
    seconds: 4.08,
    text: "Ooh, a brand new game... I can't wait!",
  },
  host_promotion_1: {
    file: 'elevenlabs-dicechess-host/host_promotion_1.mp3',
    seconds: 3.52,
    text: 'Look! That little pawn grew up!',
  },
  host_promotion_2: {
    file: 'elevenlabs-dicechess-host/host_promotion_2.mp3',
    seconds: 4.64,
    text: 'A pawn crossed the whole board! Amazing!',
  },
  host_promotion_3: {
    file: 'elevenlabs-dicechess-host/host_promotion_3.mp3',
    seconds: 3.44,
    text: 'Ta-da! The pawn got a big upgrade!',
  },
  host_white_wins_1: {
    file: 'elevenlabs-dicechess-host/host_white_wins_1.mp3',
    seconds: 4.08,
    text: 'White wins! What a game, both of you!',
  },
  host_white_wins_2: {
    file: 'elevenlabs-dicechess-host/host_white_wins_2.mp3',
    seconds: 4.64,
    text: 'Victory for White! You both played great!',
  },
  host_white_wins_3: {
    file: 'elevenlabs-dicechess-host/host_white_wins_3.mp3',
    seconds: 4.56,
    text: 'Hooray, White! And hooray, Black, too!',
  },
  host_win_1: {
    file: 'elevenlabs-dicechess-host/host_win_1.mp3',
    seconds: 3.44,
    text: "And that's the game! Bravo, you two!",
  },
  host_win_2: {
    file: 'elevenlabs-dicechess-host/host_win_2.mp3',
    seconds: 4.32,
    text: 'We have a winner! Great game, everyone!',
  },
  prowla_host_again_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_again_1.mp3',
    seconds: 4.56,
    text: "Another round? Oh, I hoped you'd say that.",
  },
  prowla_host_again_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_again_2.mp3',
    seconds: 3.84,
    text: 'Again? My tail is twitching already.',
  },
  prowla_host_again_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_again_3.mp3',
    seconds: 3.52,
    text: 'Fresh board, fresh chase. Off you go.',
  },
  prowla_host_again_4: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_again_4.mp3',
    seconds: 3.76,
    text: 'Back so soon? I adore a rematch.',
  },
  prowla_host_black_wins_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_black_wins_1.mp3',
    seconds: 3.92,
    text: 'Black takes the game! Lovely, you two.',
  },
  prowla_host_black_wins_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_black_wins_2.mp3',
    seconds: 3.28,
    text: 'The game goes to Black. Well played, White.',
  },
  prowla_host_black_wins_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_black_wins_3.mp3',
    seconds: 4.56,
    text: 'Black pounces last. What a chase, darlings.',
  },
  prowla_host_capture_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_1.mp3',
    seconds: 3.44,
    text: 'Caught! One piece leaves the board.',
  },
  prowla_host_capture_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_2.mp3',
    seconds: 4.24,
    text: 'Pounce! Someone was paying attention.',
  },
  prowla_host_capture_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_3.mp3',
    seconds: 4.08,
    text: 'Mmm, a capture. Things are warming up.',
  },
  prowla_host_capture_4: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_4.mp3',
    seconds: 3.44,
    text: 'Off it goes. The board breathes a little.',
  },
  prowla_host_capture_5: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_5.mp3',
    seconds: 3.04,
    text: 'Shh... a piece just slipped away.',
  },
  prowla_host_capture_6: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_6.mp3',
    seconds: 3.28,
    text: 'A tidy little catch. Purrr...',
  },
  prowla_host_capture_heavy_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_heavy_1.mp3',
    seconds: 4.24,
    text: 'Oh my! A big piece leaves the board.',
  },
  prowla_host_capture_heavy_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_heavy_2.mp3',
    seconds: 3.2,
    text: 'Now that was a proper pounce.',
  },
  prowla_host_capture_heavy_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_heavy_3.mp3',
    seconds: 3.6,
    text: 'My whiskers felt that one, darlings.',
  },
  prowla_host_capture_heavy_4: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_heavy_4.mp3',
    seconds: 4,
    text: 'What a catch! The whole board shivers.',
  },
  prowla_host_capture_heavy_5: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_heavy_5.mp3',
    seconds: 4.08,
    text: 'A grand piece gone. Now it gets serious.',
  },
  prowla_host_capture_queen_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_queen_1.mp3',
    seconds: 6,
    text: 'A queen falls! Oh, I adore drama.',
  },
  prowla_host_capture_queen_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_queen_2.mp3',
    seconds: 4.4,
    text: 'A queen... gone. Breathe, darlings.',
  },
  prowla_host_capture_queen_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_queen_3.mp3',
    seconds: 4.08,
    text: 'The queen! Now we have a game.',
  },
  prowla_host_capture_queen_4: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_capture_queen_4.mp3',
    seconds: 4.64,
    text: 'Farewell, Your Majesty. What a moment.',
  },
  prowla_host_draw_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_draw_1.mp3',
    seconds: 4.08,
    text: 'A draw! Two paws, perfectly matched.',
  },
  prowla_host_draw_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_draw_2.mp3',
    seconds: 2.96,
    text: 'All even, darlings. Shake paws.',
  },
  prowla_host_draw_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_draw_3.mp3',
    seconds: 4.56,
    text: 'A draw! You two are far too well matched.',
  },
  prowla_host_empty_roll_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_empty_roll_1.mp3',
    seconds: 4.32,
    text: 'The dice say no. Pass it along, darling.',
  },
  prowla_host_empty_roll_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_empty_roll_2.mp3',
    seconds: 4.64,
    text: 'No move at all? The dice are teasing.',
  },
  prowla_host_empty_roll_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_empty_roll_3.mp3',
    seconds: 3.52,
    text: 'Nothing to play? Even a cat must wait.',
  },
  prowla_host_empty_roll_4: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_empty_roll_4.mp3',
    seconds: 3.52,
    text: 'The dice took a catnap. Next turn.',
  },
  prowla_host_empty_roll_5: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_empty_roll_5.mp3',
    seconds: 4.16,
    text: 'No move... patience, darlings, patience.',
  },
  prowla_host_en_passant_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_en_passant_1.mp3',
    seconds: 3.36,
    text: 'En passant! Caught in passing, darlings.',
  },
  prowla_host_en_passant_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_en_passant_2.mp3',
    seconds: 4,
    text: 'Sneaky! A pawn caught en passant.',
  },
  prowla_host_en_passant_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_en_passant_3.mp3',
    seconds: 3.44,
    text: 'Psst... that sideways catch is en passant.',
  },
  prowla_host_handoff_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_handoff_1.mp3',
    seconds: 3.28,
    text: "Now pass the remote, darling. Black's turn.",
  },
  prowla_host_handoff_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_handoff_2.mp3',
    seconds: 4.08,
    text: 'Paw it over. The remote moves every turn.',
  },
  prowla_host_handoff_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_handoff_3.mp3',
    seconds: 3.28,
    text: 'Remote to Black, please. Gently now.',
  },
  prowla_host_intro_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_intro_1.mp3',
    seconds: 4.48,
    text: 'Two players, one board. How delicious.',
  },
  prowla_host_intro_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_intro_2.mp3',
    seconds: 4.32,
    text: "Mmm, a game for two. I'll watch from here.",
  },
  prowla_host_intro_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_intro_3.mp3',
    seconds: 3.36,
    text: 'Welcome, darlings. White rolls first.',
  },
  prowla_host_intro_4: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_intro_4.mp3',
    seconds: 3.44,
    text: "Don't mind me... I'm only here to purr.",
  },
  prowla_host_intro_5: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_intro_5.mp3',
    seconds: 3.76,
    text: 'No dice for me, darlings. I only watch.',
  },
  prowla_host_promotion_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_promotion_1.mp3',
    seconds: 4.08,
    text: 'A pawn crossed the board! How bold.',
  },
  prowla_host_promotion_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_promotion_2.mp3',
    seconds: 3.68,
    text: 'Look who grew up. A brand new piece!',
  },
  prowla_host_promotion_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_promotion_3.mp3',
    seconds: 3.68,
    text: 'From little pawn to something grand.',
  },
  prowla_host_promotion_4: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_promotion_4.mp3',
    seconds: 3.76,
    text: 'All the way across? Well done, little one.',
  },
  prowla_host_white_wins_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_white_wins_1.mp3',
    seconds: 4.08,
    text: 'White wins! Bravo, both of you.',
  },
  prowla_host_white_wins_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_white_wins_2.mp3',
    seconds: 3.44,
    text: 'The game goes to White. Well played, Black.',
  },
  prowla_host_white_wins_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_white_wins_3.mp3',
    seconds: 4,
    text: 'White takes it. What a chase, you two.',
  },
  prowla_host_win_1: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_win_1.mp3',
    seconds: 3.92,
    text: 'And the game is caught. Bravo, you two.',
  },
  prowla_host_win_2: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_win_2.mp3',
    seconds: 4.88,
    text: 'We have a winner. Purrr... beautifully done.',
  },
  prowla_host_win_3: {
    file: 'elevenlabs-dicechess-host-prowla/prowla_host_win_3.mp3',
    seconds: 4.32,
    text: "That's the game, darlings. What fun.",
  },
  rampage_capture_1: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_1.mp3',
    seconds: 4.64,
    text: 'Obliterated! One less obstacle in my path.',
  },
  rampage_capture_2: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_2.mp3',
    seconds: 4.4,
    text: 'Cut down! Your ranks crumble before me.',
  },
  rampage_capture_3: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_3.mp3',
    seconds: 3.68,
    text: 'Pathetic defense! Smashed aside!',
  },
  rampage_capture_heavy_1: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_heavy_1.mp3',
    seconds: 4.64,
    text: 'Crushed! Your mightiest defender falls into dust!',
  },
  rampage_capture_heavy_2: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_heavy_2.mp3',
    seconds: 5.84,
    text: 'Devastating strike! You cannot withstand my assault!',
  },
  rampage_capture_heavy_3: {
    file: 'elevenlabs-dicechess-bots/rampage_capture_heavy_3.mp3',
    seconds: 4.64,
    text: 'Your high command is broken! Smashed to pieces!',
  },
  rampage_empty_roll_1: {
    file: 'elevenlabs-dicechess-bots/rampage_empty_roll_1.mp3',
    seconds: 5.2,
    text: 'The dice stall my fury. Savor your brief respite.',
  },
  rampage_empty_roll_2: {
    file: 'elevenlabs-dicechess-bots/rampage_empty_roll_2.mp3',
    seconds: 5.44,
    text: 'No targets?! Unacceptable! Next turn you fall.',
  },
  rampage_empty_roll_3: {
    file: 'elevenlabs-dicechess-bots/rampage_empty_roll_3.mp3',
    seconds: 3.52,
    text: 'A momentary pause before the storm resumes.',
  },
  rampage_intro_1: {
    file: 'elevenlabs-dicechess-bots/rampage_intro_1.mp3',
    seconds: 5.28,
    text: 'Step forward. Your king will not survive this day.',
  },
  rampage_intro_2: {
    file: 'elevenlabs-dicechess-bots/rampage_intro_2.mp3',
    seconds: 5.2,
    text: 'No mercy. No retreat. Let the battle begin.',
  },
  rampage_intro_3: {
    file: 'elevenlabs-dicechess-bots/rampage_intro_3.mp3',
    seconds: 4.56,
    text: 'Prepare yourself! I strike without hesitation.',
  },
  rampage_loss_1: {
    file: 'elevenlabs-dicechess-bots/rampage_loss_1.mp3',
    seconds: 3.84,
    text: 'Impossible! How could my onslaught fail?!',
  },
  rampage_loss_2: {
    file: 'elevenlabs-dicechess-bots/rampage_loss_2.mp3',
    seconds: 5.52,
    text: 'You fought fiercely... I acknowledge your triumph.',
  },
  rampage_loss_3: {
    file: 'elevenlabs-dicechess-bots/rampage_loss_3.mp3',
    seconds: 4.96,
    text: 'Downed, but not broken! We will battle again!',
  },
  rampage_threat_1: {
    file: 'elevenlabs-dicechess-bots/rampage_threat_1.mp3',
    seconds: 2.8,
    text: 'Your king is in my sights!',
  },
  rampage_threat_2: {
    file: 'elevenlabs-dicechess-bots/rampage_threat_2.mp3',
    seconds: 3.44,
    text: 'The right roll, and your king falls!',
  },
  rampage_threat_3: {
    file: 'elevenlabs-dicechess-bots/rampage_threat_3.mp3',
    seconds: 4.24,
    text: "I can smell your king's fear!",
  },
  rampage_win_1: {
    file: 'elevenlabs-dicechess-bots/rampage_win_1.mp3',
    seconds: 5.84,
    text: 'Total annihilation! Kneel before the conqueror!',
  },
  rampage_win_2: {
    file: 'elevenlabs-dicechess-bots/rampage_win_2.mp3',
    seconds: 5.04,
    text: 'Your army is crushed beneath my heel!',
  },
  rampage_win_3: {
    file: 'elevenlabs-dicechess-bots/rampage_win_3.mp3',
    seconds: 4.96,
    text: 'Victory was inevitable! You were completely outmatched!',
  },
  rolly_capture_1: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_1.mp3',
    seconds: 2.88,
    text: 'Boop! Mine now!',
  },
  rolly_capture_2: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_2.mp3',
    seconds: 3.12,
    text: 'Got one! Every little piece counts!',
  },
  rolly_capture_3: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_3.mp3',
    seconds: 2.8,
    text: 'Snack time for my pieces!',
  },
  rolly_capture_heavy_1: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_heavy_1.mp3',
    seconds: 4.48,
    text: 'Whoa! Did I really just grab that big piece?!',
  },
  rolly_capture_heavy_2: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_heavy_2.mp3',
    seconds: 4.72,
    text: 'Look what I found! Down goes a heavy hitter!',
  },
  rolly_capture_heavy_3: {
    file: 'elevenlabs-dicechess-bots/rolly_capture_heavy_3.mp3',
    seconds: 3.84,
    text: 'Yay! That was a huge capture!',
  },
  rolly_empty_roll_1: {
    file: 'elevenlabs-dicechess-bots/rolly_empty_roll_1.mp3',
    seconds: 4.4,
    text: 'Oops, nowhere to go! Your turn!',
  },
  rolly_empty_roll_2: {
    file: 'elevenlabs-dicechess-bots/rolly_empty_roll_2.mp3',
    seconds: 4.08,
    text: "Nothing to move? That's dice for you!",
  },
  rolly_empty_roll_3: {
    file: 'elevenlabs-dicechess-bots/rolly_empty_roll_3.mp3',
    seconds: 4.64,
    text: 'A blank roll! Well, that was silly!',
  },
  rolly_intro_1: {
    file: 'elevenlabs-dicechess-bots/rolly_intro_1.mp3',
    seconds: 3.04,
    text: "Hey! Let's roll and see what happens!",
  },
  rolly_intro_2: {
    file: 'elevenlabs-dicechess-bots/rolly_intro_2.mp3',
    seconds: 4.48,
    text: "Dice ready, board ready! Let's have fun!",
  },
  rolly_intro_3: {
    file: 'elevenlabs-dicechess-bots/rolly_intro_3.mp3',
    seconds: 4.24,
    text: "I love rolling dice! Hope they're friendly today!",
  },
  rolly_loss_1: {
    file: 'elevenlabs-dicechess-bots/rolly_loss_1.mp3',
    seconds: 4.8,
    text: 'Aww, good game! You got me fair and square!',
  },
  rolly_loss_2: {
    file: 'elevenlabs-dicechess-bots/rolly_loss_2.mp3',
    seconds: 4.64,
    text: 'My king tripped! Nice catch!',
  },
  rolly_loss_3: {
    file: 'elevenlabs-dicechess-bots/rolly_loss_3.mp3',
    seconds: 4.32,
    text: "You're too good! Let's play another round!",
  },
  rolly_threat_1: {
    file: 'elevenlabs-dicechess-bots/rolly_threat_1.mp3',
    seconds: 3.84,
    text: 'Ooh! Your king is right in my path!',
  },
  rolly_threat_2: {
    file: 'elevenlabs-dicechess-bots/rolly_threat_2.mp3',
    seconds: 4.4,
    text: 'One lucky roll and your king goes boop!',
  },
  rolly_threat_3: {
    file: 'elevenlabs-dicechess-bots/rolly_threat_3.mp3',
    seconds: 2.88,
    text: 'Psst... your king might want to hide!',
  },
  rolly_win_1: {
    file: 'elevenlabs-dicechess-bots/rolly_win_1.mp3',
    seconds: 3.28,
    text: 'Yay, I won! Can we roll again?!',
  },
  rolly_win_2: {
    file: 'elevenlabs-dicechess-bots/rolly_win_2.mp3',
    seconds: 4.8,
    text: 'Woohoo! The dice were super friendly today!',
  },
  rolly_win_3: {
    file: 'elevenlabs-dicechess-bots/rolly_win_3.mp3',
    seconds: 4,
    text: 'High five! That was so much fun!',
  },
};
